version: 0.2

phases:
  install:
    commands:
      - echo "Installing PHP dependencies..."

  pre_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker image to ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 767397811981.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo "Preparing application for deployment..."
      - docker build -t test-repository .
      - docker tag test-repository:latest 767397811981.dkr.ecr.us-east-1.amazonaws.com/test-repository:latest

  post_build:
    commands:
      - echo "Running any additional tasks after the build"
      - docker push 767397811981.dkr.ecr.us-east-1.amazonaws.com/test-repository:latest
      - printf '[{"name":"test-container-definition-name","imageUri":"%s"}]' 767397811981.dkr.ecr.us-east-1.amazonaws.com/test-repository:latest > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - '**/*'
    - imagedefinitions.json

cache:
  paths:
    - vendor/**/* 
    - node_modules/**/*
